name: Build docker image and deploy it to GCP artifact repository

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: authenticate GCP
      env:
        GOOGLE_PROJECT: ${{ SECRETS.GOOGLE_PROJECT }}
      run:
        gcloud auth configure-docker us-central1-docker.pkg.dev
        
    - name: build docker image
      env:
        GOOGLE_PROJECT: ${{ SECRETS.GOOGLE_PROJECT }}
      run: 
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/yt-web-client-repo/yt-web-client ./../yt-web-client
    
    - name: push newly built docker image to GCP artifact repository
      env:
          GOOGLE_PROJECT: ${{ SECRETS.GOOGLE_PROJECT }}
      run:
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/yt-web-client-repo/yt-web-client
      

    